### ISSUE TITLE
2.2.38 nacos注册有个bug 不管ephemeral设置什么都没法注册

### ISSUE THREAD

**Issue by chixiangani** [hyperf/service-governance-nacos#5]
PHP Fatal error:  Uncaught Hyperf\Nacos\Exception\RequestException: Failed to create nacos instance 172.17.0.2:9504! for PoolService , caused: errCode: 400, errMsg: Current service DEFAULT_GROUP@@PoolService is persistent service, can't register ephemeral instance. ;  in /data/project/points/vendor/hyperf/service-governance-nacos/src/NacosDriver.php:127
Stack trace:
#0 /data/project/points/vendor/hyperf/service-governance/src/Listener/RegisterServiceListener.php(88): Hyperf\ServiceGovernanceNacos\NacosDriver->register() #1 /data/project/points/vendor/hyperf/event/src/EventDispatcher.php(48): Hyperf\ServiceGovernance\Listener\RegisterServiceListener->process()
#2 /data/project/points/vendor/hyperf/framework/src/Bootstrap/WorkerStartCallback.php(50): Hyperf\Event\EventDispatcher->dispatch()
#3 {main}
  thrown in /data/project/points/vendor/hyperf/service-governance-nacos/src/NacosDriver.php on line 127

Fatal error: Uncaught Hyperf\Nacos\Exception\RequestException: Failed to create nacos instance 172.17.0.2:9504! for PoolService , caused: errCode: 400, errMsg: Current service DEFAULT_GROUP@@PoolService is persistent service, can't register ephemeral instance. ;  in /data/project/points/vendor/hyperf/service-governance-nacos/src/NacosDriver.php:127
Stack trace:
#0 /data/project/points/vendor/hyperf/service-governance/src/Listener/RegisterServiceListener.php(88): Hyperf\ServiceGovernanceNacos\NacosDriver->register() #1 /data/project/points/vendor/hyperf/event/src/EventDispatcher.php(48): Hyperf\ServiceGovernance\Listener\RegisterServiceListener->process()
#2 /data/project/points/vendor/hyperf/framework/src/Bootstrap/WorkerStartCallback.php(50): Hyperf\Event\EventDispatcher->dispatch()
#3 {main}
  thrown in /data/project/points/vendor/hyperf/service-governance-nacos/src/NacosDriver.php on line 127

**Comment by chixiangani** [comment]
> log:
> 
> PHP Fatal error: Uncaught Hyperf\Nacos\Exception\RequestException: Failed to create nacos instance 172.17.0.2:9504! for PoolService , caused: errCode: 400, errMsg: Current service DEFAULT_GROUP@@poolservice is persistent service, can't register ephemeral instance. ; in /data/project/points/vendor/hyperf/service-governance-nacos/src/NacosDriver.php:127 Stack trace: #0 /data/project/points/vendor/hyperf/service-governance/src/Listener/RegisterServiceListener.php(88): Hyperf\ServiceGovernanceNacos\NacosDriver->register() #1 /data/project/points/vendor/hyperf/event/src/EventDispatcher.php(48): Hyperf\ServiceGovernance\Listener\RegisterServiceListener->process() #2 /data/project/points/vendor/hyperf/framework/src/Bootstrap/WorkerStartCallback.php(50): Hyperf\Event\EventDispatcher->dispatch() #3 {main} thrown in /data/project/points/vendor/hyperf/service-governance-nacos/src/NacosDriver.php on line 127

**Comment by zxyfaxcn** [comment]
我记得这里要写字符"true" "false", 你试试

**Comment by chixiangani** [comment]
解决了 为什么以前版本都不要设置ephemeral  现在要硬配置 是出于什么考虑
